
dist: xenial
language: python
cache: pip

services:
  - docker

before_install:
  - docker pull elgalu/selenium
  - docker pull dosel/zalenium
  - docker pull rubytester/browsermob-proxy
  - docker pull trinitronx/python-simplehttpserver

install:
  - pip install tox-travis
  - pip install codecov

matrix:
  include:
    - python: 2.7
      env:
        - TOX_ENV=py27
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.7
      env:
        - TOX_ENV=py37

script:
  - tox -e $TOX_ENV

after_success:
  - codecov

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: HHM9OuzgEnKRGJqgZu/mFKNZ51E95EL2t2MrQUmugvS0Q6fE5E4S8seQLJLLnLiHgmDqr45ANQFKGe3mF61SixcDFolMV3OdsRztKl1fKBxYrGBr/CAMVQe5cNpNVHQk7rnlTHdIOt+4dr4/ezZVbSIHHZifenAYvQoA+SflzPN5McwVL9EI7PEa8c4uibp4v9C6ZFh2CXxtICmlsSkxGri0iX56OLrk8Ni5oHXFsP0WUiQVp1nbMtiaREv1cp5nyAhtuph0pyuIUNkeLLzdx+dHRILdVnLf4vk7kZAWCxGJkyS7+ZoLZ8y64EwMkue4+jjBsEnVR5PQyMw6RwnhUto26il8uJ1Fy0EPKcG7WP1LOL3JMFRWEB5N3oEMuXpo7jyN6dK0ANi7JT2vmPQEWbs6mO2yvlbtvWcZIl/QoLVWdR2+AryGgARWD4pck5t2oCi4oXfLLFXGn8qyeLYNYm0g7MW9EgrHkNecMVPf2UCkFCImaAFxYYLzFC+XQXPGNds1pLEgfYxUnk0ProOskGuheG4bzNDjWol+kaX3vzERzWTJIBsm5rHpOppdqQGZHga+83Y0v0oWRdyUAoqwaoVxl3B0/eOkNX9wM1TbGIiAS5aSwOf3UJOKvtmuNlJsOK8tYq/XxWY/yI6/96N8esK36Zp1iEfR4z8pUb+8Q5w=
  skip_existing: true
  skip_cleanup: true
  on:
    branch: master
    python: '3.7'