
dist: xenial
language: python

python:
  - '2.7'

services:
  - docker

before_install:
  - docker pull elgalu/selenium
  - docker pull dosel/zalenium
  - docker rubytester/browsermob-proxy
  - docker pull trinitronx/python-simplehttpserver

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - test.sh

deploy:
  provider: pypi
  user:
  password:
  on:
    branch: master